package br.com.zup.minha__musica_favorita

const val BITA_E_O_CIRCO = "Bita e o Circo"
const val ANO_BITA_E_O_CIRCO = "Ano = 2020\nProdução : Mr. Plot"
const val DESCRICAO_CIRCO = "Que rufem os tambores! O picadeiro vira palco de Bita, Lila, Dan, Tito, Flora e mais personagens do universo circense. A diversão e todas as histórias de “Bita e o Circo” serão transformadas em aprendizado para os pequenos por meio de músicas autorais."
const val BITA_E_O_NOSSO_MUNDO = " Bita e o Nosso Mundo"
const val ANO_NOSSO_MUNDO = "Ano 2019\n Produção : Mr. Plot"
const val DESCRICAO_NOSSO_MUNDO = "Nesta temporada, cada clipe traz um pouquinho do que está ao redor da criançada, divertindo e educando com amor"
const val BITA_E_A_NATUREZA = "Bita e a Natureza"
const val ANO_NATUREZA = "Ano 2017\n Produção : Sonic Music"
const val DESCRICAO_NATUREZA =
    "O que nos cerca, o que faz parte do universo, do planeta e a própria concepção da vida. Tudo isso é natureza e está contemplado nesta temporada. Cada música traz um tema relacionado à natureza, como as águas, Montanhas, Fauna, Flora, espaço sideral, nascimento, clima e até reciclagem, sempre com mensagens educativas, construtivas e divertidas.\n" +
            "\n O Mundo Bita é feito de músicas, cores, aprendizado e alegria. Tudo com muito carinho para que pequenos e adultos brinquem e cresçam juntos. "
const val BITA_E_O_CORPO_HUMANO = " Bita e o Corpo Humano"
const val ANO_CORPO_HUMANO = "Ano 2016\n Produção : Sony Music"
const val DESCRICAO_HUMANO = "Cabeça, olhos, membros, boca, coração, cada uma das partes básicas do corpo humano é apresentada com criatividade através dos clipes musicais em desenho animado do Mundo Bita."
const val BITA_E_O_NOSSO_DIA = "Bita e o Nosso Dia"
const val ANO_NOSSO_DIA = "Ano: 2015\n Produção: Sony music "
const val DESCRICAO_NOSSO_DIA = "Temas como acordar, tomar banho, comer e ir à escola estão presentes na vida de toda criança. Vamos falar desses diferentes momentos da rotina infantil, estimulando as crianças com muita poesia e diversão? "
const val BITA_E_OS_ANIMAIS = "Bita e os animais"
const val ANO_E_OS_ANIMAIS = " Ano 2013\n Produção : Sonyc Music"
const val DESCRICAO_ANIMAIS = "Apresenta o maravilhoso mundo dos animais para toda a criançada de forma educativa e dinâmica através de clipes musicais. No primeiro DVD da turminha, cada canção aborda um ambiente e seus bichos. Da fazendinha ao fundo do mar, do safari à época dos dinossauros, tudo é repleto de encanto e ritmo. Lançado em 2013, o DVD conquistou Disco de Ouro pela Sony Music."
const val BITA_E_OS_SENTIMETOS = "Bita e os Sentimentos"
const val ANO_SENTIMENTOS = "Ano : 2022 \n Produção: Sony Music"
const val DESCRICAO_SENTIMENTO = "A música de estreia fala sobre uma emoção potente e transformadora que está presente nas pequenas ações e nos gestos mais singelos, o AMOR. Dando início ao ano e à série Bita e os Sentimentos com o pé direito, a turminha convidou o rapper Emicida, para uma participação no projeto e, juntos, criaram a música o clipe “O amor é tudo de bom” \n Abordando a importância de saber reconhecer os sentimentos e lidar com eles."
const val BITA_E_NOSSO_MUNDO2 = " Bita e o nosso Mundo 2"
const val ANO_BITA_MUNDO2 = "Ano 2021\n Produção : Sony Music"
const val DESCRICAO_MUNDO2 = "A temporada Bita e o Nosso Mundo 2 foi pensada e planejada para apresentar temas abrangentes que fazem parte da rotina infantil, dando continuidade a Bita e o Nosso Mundo, lançada em 2018.  Ao todo são dez músicas, que estimulam as crianças a lidarem com suas próprias emoções, a entenderem melhor o ambiente, as pessoas e os conceitos que permeiam os primeiros anos de vida "
const val CHAVE_ALBUM = "CHAVE_BITA"